# Generated by Django 4.1.3 on 2023-03-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Photo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Teacher_Signup',
            },
        ),
    ]
