# Generated by Django 4.2 on 2023-04-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Qualification',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
