# Generated by Django 4.2 on 2023-04-26 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('teachermanagement', '0002_myuser_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSubJect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject.adsubject')),
                ('teacherid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachermanagement.myuser')),
            ],
            options={
                'db_table': 'teacher_subject',
            },
        ),
    ]
