# Generated by Django 4.1.3 on 2023-03-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StEmail', models.CharField(max_length=100)),
                ('StPassword', models.CharField(max_length=100)),
                ('StName', models.CharField(max_length=100)),
                ('StMobile', models.CharField(max_length=100)),
                ('StGender', models.CharField(max_length=100)),
                ('StAddress', models.CharField(max_length=100)),
                ('StPhoto', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Student_Signup',
            },
        ),
    ]
