# Generated by Django 4.1.3 on 2023-03-25 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='MyUser1',
        ),
    ]
