# Generated by Django 4.2 on 2023-04-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagement', '0002_rename_myuser_myuser1'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser1',
            name='SClass',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
