# Generated by Django 4.2 on 2023-04-27 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admincourse', '0001_initial'),
        ('studentmanagement', '0003_myuser1_sclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admincourse.adcourse')),
                ('studentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentmanagement.myuser1')),
            ],
            options={
                'db_table': 'student_request',
            },
        ),
    ]
