# Generated by Django 4.2 on 2023-04-26 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admincourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adsubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('courseid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admincourse.adcourse')),
            ],
            options={
                'db_table': 'Adminsubject',
            },
        ),
    ]
